name: Deploy to Public HTML

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar para deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1' # ou a versão que seu projeto utiliza

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: npm install

      # Passo 4: Construir o projeto Angular
      - name: Build Angular project
        run: npm run build --prod

      # Passo 5: Enviar os arquivos para o servidor (usando SFTP ou FTP)
      - name: Deploy to server using SCP
        uses: appleboy/scp-action@v0.1.4
        with:
            host: ${{ secrets.FTP_SERVER }}
            username: ${{ secrets.FTP_USER }}
            password: ${{ secrets.FTP_PASSWORD }}
            port: 22
            source: "/home/runner/work/angular-web-editais/angular-web-editais/dist/editais-web/*"
            target: "/domains/systemsgf.com.br/public_html/projeto-teste"

          